### PR TITLE
fix build description for debian (jessie)

### PR DESCRIPTION
**Pull request by azet**
This way it'll actually build and have all dependencies :)

Cool project, thanks for writing this.

### CODE REVIEW

**Comment by sanderfoobar** [comment]
Yo dude, actually the `python-wifi` package is defined in _setup.py_ so it should install when you do `python setup.py develop`. That just leaves the sudo stuff for which you can modify the current pull request. Thanks for your interest.

**Comment by azet** [comment]
That's weird because running the `setup.py` script did **not** install the wifi package.

```
1 azet@orpheus ~/projects/github/upc_keys.py (git)-[master] % crack-upc                          :(
Traceback (most recent call last):
  File "/usr/local/bin/crack-upc", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: wifi
```

**Comment by azet** [comment]
BTW, also these URLs are wrong in `setup.py`:

``` Python
    url='https://github.com/skftn/crack-upc/',
    download_url='https://github.com/skftn/crack-upc/tarball/v%s' % __version__,
```

**Comment by sanderfoobar** [comment]
There is indeed something wrong with _setup.py_ on Jessie. I will remove the `python-wifi` requirement and use `network-manager` instead, like it should anyway. Ill merge this. Cheers for your help :+1:

**Pull request merged**
