### PR TITLE
Support for OS X

### PR DESCRIPTION
**Pull request by xxdavid**
I've ported it to work under OS X (tested on 10.11).
Needs a testing under Linux again.

I also added better SSID validation and fixed a bug with printing single WiFi results.

### CODE REVIEW

**Comment by sanderfoobar** [comment]
cool dude. Allow me to test both platforms and ill merge.

**Comment by dschallert** [comment]
nice but OSX does not support nmcli...

	[+] AyE, g0t 15 kEyZ, wAnnA try 'm?
	errr (y/N) y
	[+] TrYiNG k3Y xxxx 0n $$ID UPCxxx ...
	ifconfig: interface None does not exist
	 ^ nope
	sh: nmcli: command not found

**Comment by sanderfoobar** [comment]
That's right, it does not. However; this fork by @xxdavid should detect you are running OSX and instead use `networksetup -setairportnetwork`. See: https://github.com/xxdavid/upc_keys.py/blob/osx/crack_upc/__main__.py#L151

Please confirm you are using his fork with the 'osx' branch.

**Comment by dschallert** [comment]
nice, seems i missed that line :+1:

**Comment by sanderfoobar** [comment]
Alright, I'm just going to merge this. Yolo. Thanks for your contribution :+1:

**Pull request merged**
